web/apps/shop/urls.py
from django.urls import path
from .views import HomePageView, AboutPageView, ContactPageView, ShopPageView, ProductDetailPageView, \
    ProductCreatePageView, FilterProductsPageView, CategoryPageView, SearchView, FavouritesView, FavouritesAddView, \
    CardView, CardAddView, CardDeleteView, FavouriteDeleteView

app_name = 'shop'
urlpatterns = [
    path('', HomePageView.as_view(), name='home'),
    path('about-us/', AboutPageView.as_view(), name='about'),
    path('contact/', ContactPageView.as_view(), name='contact'),
    path('filter/', FilterProductsPageView.as_view(), name='filter'),
    path('shop/search/', SearchView.as_view(), name='search'),
    path('shop/category/<int:id>', CategoryPageView.as_view(), name='category'),
    path('shop/', ShopPageView.as_view(), name='shop'),
    path('products/<int:pk>', ProductDetailPageView.as_view(), name='product-detail'),
    path('product-create/', ProductCreatePageView.as_view(), name='product-create'),
    path('favourites/', FavouritesView.as_view(), name='favourite-list'),
    path('favourite-add/<int:product_id>/', FavouritesAddView.as_view(), name='favourite-add'),
    path('favourite-delete/<int:product_id>/', FavouriteDeleteView.as_view(), name='favourite-delete'),
    path('cards/', CardView.as_view(), name='card-list'),
    path('card-add/<int:product_id>/', CardAddView.as_view(), name='card-add'),
    path('card-delete/<int:product_id>/', CardDeleteView.as_view(), name='card-delete'),
]

web/apps/users/urls.py
from django.urls import path

from apps.users.views import UserLoginView, register_view, UserProfileView, logout_view, user_update_view, UserUpdateView

app_name = 'users'
urlpatterns = [
    path('login/', UserLoginView.as_view(), name="login"),
    # path('register/', UserRegisterView.as_view(), name="register"),
    path('register/', register_view, name="register"),
    path('user-profile/', UserProfileView.as_view(), name="user-profile"),
    path('user-update/', UserUpdateView.as_view(), name="user-update"),
    # path('user-update/', user_update_view, name="user-update"),
    # path('user-update/<int:id>', UserUpdateView.as_view(), name="user-update"),
    path('logout/', logout_view, name="logout"),
]

web/config/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from config import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('apps.store.urls')),
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

web/apps/shop/forms.py
from django.forms import ModelForm, IntegerField, Widget, Textarea, FileField, ImageField, FileInput

from apps.shop.models import Product, ProductReview


class ProductForm(ModelForm):
    cover = FileField(widget=FileInput(attrs={'class': 'form-control'}))

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields:
            if str(field) != "is_active":
                self.fields[field].widget.attrs.update(
                    {'class': 'form-control', 'placeholder': f'Enter the {str(field)}'}
                )

    class Meta:
        model = Product
        fields = (
            'name', 'price', 'description', 'category_slug', 'brand_slug', 'color', 'sub_category', 'published_date', 'cover', 'is_active', 'slug')


class ProductUpdateForm(ModelForm):
    class Meta:
        model = Product
        fields = '__all__'


class ProductReviewForm(ModelForm):
    class Meta:
        model = ProductReview
        fields = ('body', 'rating')
        widgets = {
            'body': Textarea(attrs={'class': 'form-control'}),
            'rating': IntegerField()
        }

web/apps/shop/views.py
from django.core.paginator import Paginator
from django.shortcuts import render, redirect, HttpResponseRedirect
from django.views.generic import TemplateView, ListView
from django.views import View
from django.contrib import messages

from apps.shop.forms import ProductForm
from apps.shop.models import Product, Category, Favorite, Card
from apps.users.models import User


# class Category:
#     def get_categories(self):
#         return Category.objects.all()


class HomePageView(View):
    def get(self, request):
        products = Product.objects.all()
        categories = Category.objects.all()

        context = {
            "products": products, "categories": categories,
        }
        return render(request, "shop/index.html", context=context)


class ProductDetailPageView(View):
    def get(self, request, pk):
        product = Product.objects.get(pk=pk)
        products = Product.objects.all()
        context = {
            "product": product,
            "products": products
        }
        return render(request, 'shop/product-detail.html', context)


class ProductCreatePageView(View):
    def get(self, request):
        form = ProductForm()
        context = {'form': form}
        return render(request, 'shop/product-create.html', context)

    def post(self, request):
        form = ProductForm(request.POST, request.FILES)
        if form.is_valid():
            product = form.save(commit=False)
            product.seller = request.user
            product.save()
            # name = form.cleaned_data.get('name'),
            # description = form.cleaned_data.get('description'),
            # available_color = form.cleaned_data.get('available_color'),
            # price = form.cleaned_data.get('price'),
            # brand = form.cleaned_data.get('brand'),
            # category = form.cleaned_data.get('category'),
            # cover = form.cleaned_data.get('cover'),
            # size = form.cleaned_data.get('size'),
            # count = form.cleaned_data.get('count'),
            # is_active = form.cleaned_data.get('is_active')
            # product = Product.objects.create(name=name,
            #                                  description=description,
            #                                  available_color=available_color,
            #                                  price=price,
            #                                  brand=brand,
            #                                  category=category,
            #                                  cover=cover,
            #                                  size=size,
            #                                  count=count,
            #                                  is_active=is_active,
            #                                  seller=request.user)
            # product.save()
            # form.save()
            return redirect('users:user-profile')
        else:
            form = ProductForm()
        context = {'form': form}
        return render(request, 'shop/product-create.html', context)


class FavoritesPageView(View):
    def get(self, request):
        favorites = Favorite.objects.filter(user=request.user)
        context = {f"favorites": favorites}
        return render(request, 'shop/favourites-list.html', context)


class BaseView(View):
    def get(self, request):
        products = Product.objects.all()
        user = request.user
        categories = Category.objects.all()
        cards = Card.objects.filter(user=user)
        favorites = Favorite.objects.filter(user=user)
        context = {'products': products, 'user': user, 'categories': categories, 'cards': cards, 'favorites': favorites}
        return render(request, 'base.html', context)


class AboutPageView(TemplateView):
    template_name = 'shop/about.html'


class ContactPageView(TemplateView):
    template_name = 'shop/contact.html'


class ShopPageView(View):
    def get(self, request):
        products = Product.objects.all()
        categories = Category.objects.all()
        paginator = Paginator(products, 3)
        page_number = request.GET.get('page')
        page_obj = paginator.get_page(page_number)
        context = {'products': products, 'categories': categories, 'page_obj': page_obj}
        return render(request, 'shop/shop.html', context)


class CategoryPageView(View):
    def get(self, request, id):
        products = Product.objects.filter(category=id)
        categories = Category.objects.all()
        paginator = Paginator(products, 3)
        page_number = request.GET.get('page')
        page_obj = paginator.get_page(page_number)
        context = {'products': products, 'categories': categories, 'page_obj': page_obj}
        return render(request, 'shop/shop.html', context)


class SearchView(ListView):
    template_name = 'shop/shop.html'
    context_object_name = 'products'
    paginate_by = 5

    def get_queryset(self):
        return Product.objects.filter(name__icontains=self.request.GET.get('q'))

    def get_context_data(self, *, objects_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        context['q'] = self.request.GET.get('q')
        return context


class FavouritesView(ListView):
    template_name = 'shop/favourites-list.html'
    model = Favorite
    context_object_name = 'favourites'


class FavouritesAddView(View):
    def get(self, request, product_id):
        user = request.user
        current_page = request.META.get('HTTP_REFERER')
        product = Product.objects.get(id=product_id)
        favourites = Favorite.objects.filter(user=user, product=product)

        if not favourites.exists():
            Favorite.objects.create(user=user, product=product, quantity=1)
            # favourite = Favorite(user=request.user, product=product, quantity=1)
            # favourite.save()
            return HttpResponseRedirect(current_page)
        else:
            favourite = favourites.first()
            favourite.quantity += 1
            favourite.save()
            return HttpResponseRedirect(current_page)


class FavouriteDeleteView(View):
    def get(self, request, favourite_id):
        favourite = Favorite.objects.get(id=favourite_id)
        favourite.delete()
        return redirect('shop:favourites-list')


class CardView(ListView):
    template_name = 'shop/card-list.html'
    model = Card
    context_object_name = 'cards'


class CardAddView(View):
    def get(self, request, product_id):
        user = request.user
        current_page = request.META.get('HTTP_REFERER')
        product = Product.objects.get(id=product_id)
        cards = Card.objects.filter(user=user, product=product)

        if not cards.exists():
            Card.objects.create(user=user, product=product, quantity=1)
            return HttpResponseRedirect(current_page)
        else:
            card = cards.first()
            card.quantity += 1
            card.save()
            return HttpResponseRedirect(current_page)


class CardDeleteView(View):
    def get(self, request, card_id):
        current_page = request.META.get('HTTP_REFERER')
        card = Card.objects.get(id=card_id)
        card.delete()
        return HttpResponseRedirect(current_page)


class FilterProductsPageView(View):
    def get_queryset(self):
        categories = Category.objects.all()
        queryset = Product.objects.filter(category=self.request.GET.getlist('category'))
        return queryset
    # def get(self):
    #     products = Product.objects.filter(category_id=self.kwargs['category_id'])
    #     return products


class ShopSinglePageView(TemplateView):
    template_name = 'shop/product-detail.html'
# def product_create(request):
#     if request.method == 'POST':
#         form = ProductForm(request.POST)
#         if form.is_valid:
#             # product = Product(name=form.cleaned_data.get('name'),
#             #                   description=form.cleaned_data.get('description'),
#             #                   available_color=form.cleaned_data.get('available_color'),
#             #                   price=form.cleaned_data.get('price'),
#             #                   brand=form.cleaned_data.get('brand'),
#             #                   category=form.cleaned_data.get('category'),
#             #                   cover=form.cleaned_data.get('cover'),
#             #                   size=form.cleaned_data.get('size'),
#             #                   count=form.cleaned_data.get('count'),
#             #                   is_active=form.cleaned_data.get('is_active'), )
#             # product = Product(name=form.cleaned_data['name'], description=form.cleaned_data['description'],
#             #                   is_active=form.cleaned_data['is_active'])
#             # product.seller = request.user
#             # product.save()
#             form.save()
#             messages.success(request, 'Post successfully created!')
#             return redirect('blog:user-profile')
#         else:
#             return render(request, 'shop/product-create.html', {'form': form})
#     else:
#         form = ProductForm()
#
#     return render(request, 'shop/product-create.html', {'form': form})

web/apps/users/views.py
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import AuthenticationForm
from django.contrib import messages
from django.shortcuts import render, redirect, get_object_or_404
from django.views import View

from apps.users.forms import UserRegisterForm, UserLoginForm, UserUpdateForm
from apps.shop.models import Product


def register_view(request):
    form = UserRegisterForm()
    if request.method == 'POST':
        form = UserRegisterForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            messages.success(request, 'User successfully registered')
            return redirect("users:login")
        else:
            return render(request, 'users/register.html', {'form': form})
    else:
        return render(request, 'users/register.html', {'form': form})


# class UserRegisterView(View):
#     def get(self, request):
#         form = UserRegisterForm()
#         return render(request, "users/register.html", context={"form": form})
#
#     def post(self, request):
#         create_form = UserRegisterForm(request.POST, request.FILES)
#         if create_form.is_valid():
#             create_form.save()
#             return redirect("users:login")
#         else:
#             context = {
#                 "form": create_form
#             }
#             return render(request, "users/register.html", context=context)


from apps.users.models import User


class UserLoginView(View):
    def get(self, request):
        form = UserLoginForm()
        context = {'form': form}
        return render(request, 'users/login.html', context)

    def post(self, request):
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            username = form.cleaned_data.get("username")
            password = form.cleaned_data.get("password")
            user = authenticate(username=username, password=password)
            if user is not None:
                login(request, user)
                messages.info(request, f"You have logged in as {username}")
                return redirect('shop:home')
            else:
                messages.error(request, "Invalid username or password")
        else:
            return render(request, "users/login.html", {"form": form})


def user_update_view(request, id):
    if request.method == 'POST':
        if request.user.is_authenticated:
            user = User.objects.get(id=request.user.id)
            form = UserUpdateForm(request.POST or None, request.FILES, instance=user)
            if form.is_valid():
                form.save()

                login(request, user)
                messages.success(request, 'User successfully updated')
                return redirect("users:user-profile")
            return render(request, 'users/user-update.html', {'form': form})
        else:
            messages.error(request, "You Must be Logged in To Access This Page!")
            return redirect("shop:home")
    else:
        form = UserUpdateForm()
        return render(request, 'users/user-update.html', {'form': form})


@login_required
def logout_view(request):
    messages.info(request, f"{request.user.username} user successfully loged out")
    logout(request)
    return redirect("shop:home")


class UserProfileView(View):
    def get(self, request):
        products = Product.objects.filter(seller__username=request.user.username)
        user = get_object_or_404(User, username=request.user.username)
        first_name = user.first_name
        last_name = user.last_name
        return render(request, 'users/user-profile.html', {"products": products,
                                                           'first_name': first_name,
                                                           'last_name': last_name,
                                                           'user': user})


class UserUpdateView(View):
    def get(self, request, id):
        user = User.objects.get(id=id)
        form = UserUpdateForm
        return render(request, 'users/user-update.html', {'form': form})

    def post(self, request):
        if request.user.is_authenticated:
            user = User.objects.get(id=request.user.id)
            form = UserUpdateForm(request.POST or None, request.FILES, instance=user)
            if form.is_valid():
                form.save()

                login(request, user)
                messages.success(request, 'User successfully updated')
                return redirect("users:user-profile")
            return render(request, 'users/user-update.html', {'form': form})
        else:
            messages.error(request, "You Must be Logged in To Access This Page!")
            return redirect("shop:home")

web/templates/shop/blog.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

		<!-- Start Hero Section -->
			<div class="hero">
				<div class="container">
					<div class="row justify-content-between">
						<div class="col-lg-5">
							<div class="intro-excerpt">
								<h1>Blog</h1>
								<p class="mb-4">Donec vitae odio quis nisl dapibus malesuada. Nullam ac aliquet velit. Aliquam vulputate velit imperdiet dolor tempor tristique.</p>
								<p><a href="" class="btn btn-secondary me-2">Shop Now</a><a href="#" class="btn btn-white-outline">Explore</a></p>
							</div>
						</div>
						<div class="col-lg-7">
							<div class="hero-img-wrap">
								<img src="{% static 'images/couch.png' %}" class="img-fluid">
							</div>
						</div>
					</div>
				</div>
			</div>
		<!-- End Hero Section -->



		<!-- Start Blog Section -->
		<div class="blog-section">
			<div class="container">

				<div class="row">

					<div class="col-12 col-sm-6 col-md-4 mb-5">
						<div class="post-entry">
							<a href="#" class="post-thumbnail"><img src="{% static 'images/post-1.jpg' %}" alt="Image" class="img-fluid"></a>
							<div class="post-content-entry">
								<h3><a href="#">First Time Home Owner Ideas</a></h3>
								<div class="meta">
									<span>by <a href="#">Kristin Watson</a></span> <span>on <a href="#">Dec 19, 2021</a></span>
								</div>
							</div>
						</div>
					</div>

					<div class="col-12 col-sm-6 col-md-4 mb-5">
						<div class="post-entry">
							<a href="#" class="post-thumbnail"><img src="{% static 'images/post-2.jpg' %}" alt="Image" class="img-fluid"></a>
							<div class="post-content-entry">
								<h3><a href="#">How To Keep Your Furniture Clean</a></h3>
								<div class="meta">
									<span>by <a href="#">Robert Fox</a></span> <span>on <a href="#">Dec 15, 2021</a></span>
								</div>
							</div>
						</div>
					</div>

					<div class="col-12 col-sm-6 col-md-4 mb-5">
						<div class="post-entry">
							<a href="#" class="post-thumbnail"><img src="{% static 'images/post-3.jpg' %}" alt="Image" class="img-fluid"></a>
							<div class="post-content-entry">
								<h3><a href="#">Small Space Furniture Apartment Ideas</a></h3>
								<div class="meta">
									<span>by <a href="#">Kristin Watson</a></span> <span>on <a href="#">Dec 12, 2021</a></span>
								</div>
							</div>
						</div>
					</div>

					<div class="col-12 col-sm-6 col-md-4 mb-5">
						<div class="post-entry">
							<a href="#" class="post-thumbnail"><img src="{% static 'images/post-1.jpg' %}" alt="Image" class="img-fluid"></a>
							<div class="post-content-entry">
								<h3><a href="#">First Time Home Owner Ideas</a></h3>
								<div class="meta">
									<span>by <a href="#">Kristin Watson</a></span> <span>on <a href="#">Dec 19, 2021</a></span>
								</div>
							</div>
						</div>
					</div>

					<div class="col-12 col-sm-6 col-md-4 mb-5">
						<div class="post-entry">
							<a href="#" class="post-thumbnail"><img src="{% static 'images/post-2.jpg' %}" alt="Image" class="img-fluid"></a>
							<div class="post-content-entry">
								<h3><a href="#">How To Keep Your Furniture Clean</a></h3>
								<div class="meta">
									<span>by <a href="#">Robert Fox</a></span> <span>on <a href="#">Dec 15, 2021</a></span>
								</div>
							</div>
						</div>
					</div>

					<div class="col-12 col-sm-6 col-md-4 mb-5">
						<div class="post-entry">
							<a href="#" class="post-thumbnail"><img src="{% static 'images/post-3.jpg' %]" alt="Image" class="img-fluid"></a>
							<div class="post-content-entry">
								<h3><a href="#">Small Space Furniture Apartment Ideas</a></h3>
								<div class="meta">
									<span>by <a href="#">Kristin Watson</a></span> <span>on <a href="#">Dec 12, 2021</a></span>
								</div>
							</div>
						</div>
					</div>

					<div class="col-12 col-sm-6 col-md-4 mb-5">
						<div class="post-entry">
							<a href="#" class="post-thumbnail"><img src="{% static 'images/post-1.jpg' %}" alt="Image" class="img-fluid"></a>
							<div class="post-content-entry">
								<h3><a href="#">First Time Home Owner Ideas</a></h3>
								<div class="meta">
									<span>by <a href="#">Kristin Watson</a></span> <span>on <a href="#">Dec 19, 2021</a></span>
								</div>
							</div>
						</div>
					</div>

					<div class="col-12 col-sm-6 col-md-4 mb-5">
						<div class="post-entry">
							<a href="#" class="post-thumbnail"><img src="{% static 'images/post-2.jpg' %}" alt="Image" class="img-fluid"></a>
							<div class="post-content-entry">
								<h3><a href="#">How To Keep Your Furniture Clean</a></h3>
								<div class="meta">
									<span>by <a href="#">Robert Fox</a></span> <span>on <a href="#">Dec 15, 2021</a></span>
								</div>
							</div>
						</div>
					</div>

					<div class="col-12 col-sm-6 col-md-4 mb-5">
						<div class="post-entry">
							<a href="#" class="post-thumbnail"><img src="{% static 'images/post-3.jpg' %}" alt="Image" class="img-fluid"></a>
							<div class="post-content-entry">
								<h3><a href="#">Small Space Furniture Apartment Ideas</a></h3>
								<div class="meta">
									<span>by <a href="#">Kristin Watson</a></span> <span>on <a href="#">Dec 12, 2021</a></span>
								</div>
							</div>
						</div>
					</div>

				</div>
			</div>
		</div>
		<!-- End Blog Section -->



		<!-- Start Testimonial Slider -->
		<div class="testimonial-section before-footer-section">
			<div class="container">
				<div class="row">
					<div class="col-lg-7 mx-auto text-center">
						<h2 class="section-title">Testimonials</h2>
					</div>
				</div>

				<div class="row justify-content-center">
					<div class="col-lg-12">
						<div class="testimonial-slider-wrap text-center">

							<div id="testimonial-nav">
								<span class="prev" data-controls="prev"><span class="fa fa-chevron-left"></span></span>
								<span class="next" data-controls="next"><span class="fa fa-chevron-right"></span></span>
							</div>

							<div class="testimonial-slider">

								<div class="item">
									<div class="row justify-content-center">
										<div class="col-lg-8 mx-auto">

											<div class="testimonial-block text-center">
												<blockquote class="mb-5">
													<p>&ldquo;Donec facilisis quam ut purus rutrum lobortis. Donec vitae odio quis nisl dapibus malesuada. Nullam ac aliquet velit. Aliquam vulputate velit imperdiet dolor tempor tristique. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Integer convallis volutpat dui quis scelerisque.&rdquo;</p>
												</blockquote>

												<div class="author-info">
													<div class="author-pic">
														<img src="{% static 'images/person-1.png' %}" alt="Maria Jones" class="img-fluid">
													</div>
													<h3 class="font-weight-bold">Maria Jones</h3>
													<span class="position d-block mb-3">CEO, Co-Founder, XYZ Inc.</span>
												</div>
											</div>

										</div>
									</div>
								</div>
								<!-- END item -->

								<div class="item">
									<div class="row justify-content-center">
										<div class="col-lg-8 mx-auto">

											<div class="testimonial-block text-center">
												<blockquote class="mb-5">
													<p>&ldquo;Donec facilisis quam ut purus rutrum lobortis. Donec vitae odio quis nisl dapibus malesuada. Nullam ac aliquet velit. Aliquam vulputate velit imperdiet dolor tempor tristique. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Integer convallis volutpat dui quis scelerisque.&rdquo;</p>
												</blockquote>

												<div class="author-info">
													<div class="author-pic">
														<img src="{% static 'images/person-1.png' %}" alt="Maria Jones" class="img-fluid">
													</div>
													<h3 class="font-weight-bold">Maria Jones</h3>
													<span class="position d-block mb-3">CEO, Co-Founder, XYZ Inc.</span>
												</div>
											</div>

										</div>
									</div>
								</div>
								<!-- END item -->

								<div class="item">
									<div class="row justify-content-center">
										<div class="col-lg-8 mx-auto">

											<div class="testimonial-block text-center">
												<blockquote class="mb-5">
													<p>&ldquo;Donec facilisis quam ut purus rutrum lobortis. Donec vitae odio quis nisl dapibus malesuada. Nullam ac aliquet velit. Aliquam vulputate velit imperdiet dolor tempor tristique. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Integer convallis volutpat dui quis scelerisque.&rdquo;</p>
												</blockquote>

												<div class="author-info">
													<div class="author-pic">
														<img src="{% static 'images/person-1.png' %}" alt="Maria Jones" class="img-fluid">
													</div>
													<h3 class="font-weight-bold">Maria Jones</h3>
													<span class="position d-block mb-3">CEO, Co-Founder, XYZ Inc.</span>
												</div>
											</div>

										</div>
									</div>
								</div>
								<!-- END item -->

							</div>

						</div>
					</div>
				</div>
			</div>
		</div>
		<!-- End Testimonial Slider -->

{% endblock %}

web/templates/shop/favourites-list.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
    <div class="container">
        <h1 class="mt-5">My favourites:</h1>
        <div class="row">
            {% for favourite in favourites %}
                {% if favourite.user == request.user %}
                    <div class="col-md-3">
                        <div class="card mb-4 product-wap rounded-0">
                            <div class="card rounded-0">
                                <img class="card-img rounded-0 img-fluid" src="{{ favourite.product.cover.url }}">
                                <div class="card-img-overlay rounded-0 product-overlay d-flex align-items-center justify-content-center">
                                    <ul class="list-unstyled">
                                        <li>
                                            <a class="btn btn-success text-white"
                                               href="{% url 'shop:favourite-add' favourite.product.id %}">
                                                <i class='far fa-heart'></i>
                                            </a>
                                        </li>
                                        <li>
                                            <a class="btn btn-success text-white mt-2"
                                               href="{% url 'shop:product-detail' favourite.product.id %}"><i
                                                class="far fa-eye"></i>
                                            </a>
                                        </li>
                                        <li>
                                            <a class="btn btn-success text-white mt-2"
                                               href="{% url 'shop:card-add' favourite.product.id %}"><i
                                                class="fas fa-cart-plus"></i>
                                            </a>
                                        </li>
                                    </ul>
                                </div>
                            </div>
                            <div class="card-body">
                                <a href="product-detail.html"
                                   class="h3 text-decoration-none">{{ favourite.product.name }}</a>
                                <ul class="w-100 list-unstyled d-flex justify-content-between mb-0">
                                    <li><span class="text-secondary fs-6">{{ favourite.product.seller.username }}</span>
                                    </li>
                                    <li class="pt-2">
                                        <span class="product-color-dot color-dot-red float-left rounded-circle ml-1"></span>
                                        <span class="product-color-dot color-dot-blue float-left rounded-circle ml-1"></span>
                                        <span class="product-color-dot color-dot-black float-left rounded-circle ml-1"></span>
                                        <span class="product-color-dot color-dot-light float-left rounded-circle ml-1"></span>
                                        <span class="product-color-dot color-dot-green float-left rounded-circle ml-1"></span>
                                    </li>
                                </ul>
                                <ul class="list-unstyled d-flex justify-content-center mb-1">
                                    <li>
                                        <i class="text-warning fa fa-star"></i>
                                        <i class="text-warning fa fa-star"></i>
                                        <i class="text-warning fa fa-star"></i>
                                        <i class="text-muted fa fa-star"></i>
                                        <i class="text-muted fa fa-star"></i>
                                    </li>
                                </ul>
                                <p class="text-center mb-0">${{ favourite.product.price }}</p>

                                <a class="btn btn-danger text-white w-100"
                                   href="{% url 'shop:favourite-delete' favourite.id %}">
                                    <i class='bx bxs-heart'></i>
                                    Delete
                                </a>
                            </div>
                        </div>
                    </div>
                {% endif %}
            {% endfor %}
        </div>
    </div>
{% endblock %}