web/apps/shop/urls.py
from django.urls import path
from .views import HomePageView, AboutPageView, ContactPageView, ShopPageView, ProductDetailPageView, \
    ProductCreatePageView, FilterProductsPageView, CategoryPageView, SearchView, FavouritesView, FavouritesAddView, \
    CardView, CardAddView, CardDeleteView, FavouriteDeleteView

app_name = 'shop'
urlpatterns = [
    path('', HomePageView.as_view(), name='home'),
    path('about-us/', AboutPageView.as_view(), name='about'),
    path('contact/', ContactPageView.as_view(), name='contact'),
    path('filter/', FilterProductsPageView.as_view(), name='filter'),
    path('shop/search/', SearchView.as_view(), name='search'),
    path('shop/category/<int:id>', CategoryPageView.as_view(), name='category'),
    path('shop/', ShopPageView.as_view(), name='shop'),
    path('products/<int:pk>', ProductDetailPageView.as_view(), name='product-detail'),
    path('product-create/', ProductCreatePageView.as_view(), name='product-create'),
    path('favourites/', FavouritesView.as_view(), name='favourite-list'),
    path('favourite-add/<int:product_id>/', FavouritesAddView.as_view(), name='favourite-add'),
    path('favourite-delete/<int:product_id>/', FavouriteDeleteView.as_view(), name='favourite-delete'),
    path('cards/', CardView.as_view(), name='card-list'),
    path('card-add/<int:product_id>/', CardAddView.as_view(), name='card-add'),
    path('card-delete/<int:product_id>/', CardDeleteView.as_view(), name='card-delete'),
]

web/apps/users/urls.py
from django.urls import path

from apps.users.views import UserLoginView, register_view, UserProfileView, logout_view, user_update_view, UserUpdateView

app_name = 'users'
urlpatterns = [
    path('login/', UserLoginView.as_view(), name="login"),
    # path('register/', UserRegisterView.as_view(), name="register"),
    path('register/', register_view, name="register"),
    path('user-profile/', UserProfileView.as_view(), name="user-profile"),
    path('user-update/', UserUpdateView.as_view(), name="user-update"),
    # path('user-update/', user_update_view, name="user-update"),
    # path('user-update/<int:id>', UserUpdateView.as_view(), name="user-update"),
    path('logout/', logout_view, name="logout"),
]

web/config/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from config import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('apps.store.urls')),
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

web/templates/base.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="author" content="Untree.co">
    <link rel="shortcut icon" href="store/favicon.png">

    <meta name="description" content=""/>
    <meta name="keywords" content="bootstrap, bootstrap4"/>

    <!-- Bootstrap CSS -->
    <link href="css/bootstrap.min.css" rel="stylesheet">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css" rel="stylesheet">
    <link href="css/tiny-slider.css" rel="stylesheet">
    <link href="{% static 'css/style.css' %}" rel="stylesheet">
    <title>Furni Free Bootstrap 5 Template for Furniture and Interior Design Websites by Untree.co </title>
</head>

<body>

<!-- Start Header/Navigation -->
<nav class="custom-navbar navbar navbar navbar-expand-md navbar-dark bg-dark" arial-label="Furni navigation bar">

    <div class="container">
        <a class="navbar-brand" href="store/index.html">Furni<span>.</span></a>
        <a class="btn btn-outline-primary" href="https://t.me/furni_store_bot">Telegram bot</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarsFurni"
                aria-controls="navbarsFurni" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <a class="collapsed d-flex justify-content-between h3 text-decoration-none" href="#">
            Categories
            <i class="fa fa-fw fa-chevron-circle-down mt-1"></i>
        </a>
        <ul class="collapse show list-unstyled pl-3">
            {% for category in categories %}
            <li>
                <a class="text-decoration-none"
                   href="{% url 'shop:category' category.id %}">{{ category.name }}</a>
                {# <input type="checkbox" class="btn-check" id="btn-check-4" autocomplete="off" #}
                          {# {# name="category" value="{{ category }}">#}
                {# <label class="btn" for="btn-check-4"><a class="text-decoration-none" #}
                                                           {# href="#">{{ category.name }}</a></label>#}
            </li>
            {% endfor %}
        </ul>
        <form action="{% url 'shop:search' %}" method="get">
            {% csrf_token %}
            <div class="col-md-8 pb-4">
                <div class="d-flex">
                    <input type="search" placeholder="Search" name="q" class="form-control">
                    <button type="submit" class="btn btn-warning"><i
                            class="fa fa-fw fa-search text-dark mr-2"></i></button>
                </div>
            </div>
        </form>

        <div class="collapse navbar-collapse" id="navbarsFurni">
            <ul class="custom-navbar-nav navbar-nav ms-auto mb-2 mb-md-0">
                <li class="nav-item active">
                    <a class="nav-link" href="store/index.html">Home</a>
                </li>
                <li><a class="nav-link" href="store/shop.html">Shop</a></li>
                <li><a class="nav-link" href="store/about.html">About us</a></li>
                <li><a class="nav-link" href="store/services.html">Services</a></li>
                <li><a class="nav-link" href="store/blog.html">Blog</a></li>
                <li><a class="nav-link" href="store/contact.html">Contact us</a></li>
            </ul>

            <ul class="custom-navbar-cta navbar-nav mb-2 mb-md-0 ms-5">
                <li><a class="nav-link" href="#"><img src="images/user.svg"></a></li>
                <li><a class="nav-link" href="store/cart.html"><img src="images/cart.svg"></a></li>
            </ul>
        </div>
    </div>

</nav>
<div class="navbar align-self-center d-flex">
    <div class="d-lg-none flex-sm-fill mt-3 mb-4 col-7 col-sm-auto pr-3">
        <div class="input-group">
            <input type="text" class="form-control" id="inputMobileSearch" placeholder="Search ...">
            <div class="input-group-text">
                <i class="fa fa-fw fa-search"></i>
            </div>
        </div>
    </div>
    <a class="nav-icon d-none d-lg-inline" href="#" data-bs-toggle="modal"
       data-bs-target="#templatemo_search">
        <i class="fa fa-fw fa-search text-dark mr-2"></i>
    </a>
    {% if request.user.is_authenticated %}
        <a class="nav-icon position-relative text-decoration-none" href="{% url 'shop:card-list' %}">
            <i class="fa fa-fw fa-cart-arrow-down text-dark mr-1"></i>
            {# <span
                class="position-absolute top-0 left-100 translate-middle badge rounded-pill bg-light text-dark">7</span>#}
        </a>
        <a class="nav-icon position-relative text-decoration-none" href="{% url 'shop:favourite-list' %}">
            <button class="btn btn-block"><i class='far fa-heart'></i></button>
        </a>
        <a class="nav-icon position-relative text-decoration-none" href="{% url 'users:user-profile' %}">
            <button class="btn navbar-btn"><i class="fa fa-fw fa-user text-dark mr-3"></i>
                {# <span
                        class="position-absolute top-0 left-100 translate-middle badge rounded-pill bg-light text-dark">+99</span>#}
                {{ user.username }}
            </button>
        </a>

        <a class="nav-icon position-relative text-decoration-none" href="{% url 'shop:product-create' %}">
            <button type="submit" class="btn btn-outline-warning">+Add</button>
        </a>
        <a class="nav-icon position-relative text-decoration-none" href="{% url 'users:logout' %}">
            <button type="submit" class="btn btn-outline-danger">Log out</button>
        </a>
    {% else %}
        <a class="nav-icon position-relative text-decoration-none" href="{% url 'users:login' %}">
            <button type="submit" class="btn btn-outline-success">Sign in</button>
            {# <span
                class="position-absolute top-0 left-100 translate-middle badge rounded-pill bg-light text-dark">+99</span>#}
        </a>
        <a class="nav-icon position-relative text-decoration-none" href="{% url 'users:register' %}">
            <button type="submit" class="btn btn-success">Sign up</button>
            {# <span
                class="position-absolute top-0 left-100 translate-middle badge rounded-pill bg-light text-dark">+99</span>#}
        </a>
    {% endif %}
</div>
<!-- End Header/Navigation -->

{% block content %}
{% endblock %}

<!-- Start Footer Section -->
<footer class="footer-section">
    <div class="container relative">

        <div class="sofa-img">
            <img src="images/sofa.png" alt="Image" class="img-fluid">
        </div>

        <div class="row">
            <div class="col-lg-8">
                <div class="subscription-form">
                    <h3 class="d-flex align-items-center"><span class="me-1"><img src="images/envelope-outline.svg"
                                                                                  alt="Image"
                                                                                  class="img-fluid"></span><span>Subscribe to Newsletter</span>
                    </h3>

                    <form action="#" class="row g-3">
                        <div class="col-auto">
                            <input type="text" class="form-control" placeholder="Enter your name">
                        </div>
                        <div class="col-auto">
                            <input type="email" class="form-control" placeholder="Enter your email">
                        </div>
                        <div class="col-auto">
                            <button class="btn btn-primary">
                                <span class="fa fa-paper-plane"></span>
                            </button>
                        </div>
                    </form>

                </div>
            </div>
        </div>

        <div class="row g-5 mb-5">
            <div class="col-lg-4">
                <div class="mb-4 footer-logo-wrap"><a href="#" class="footer-logo">Furni<span>.</span></a></div>
                <p class="mb-4">Donec facilisis quam ut purus rutrum lobortis. Donec vitae odio quis nisl dapibus
                    malesuada. Nullam ac aliquet velit. Aliquam vulputate velit imperdiet dolor tempor tristique.
                    Pellentesque habitant</p>

                <ul class="list-unstyled custom-social">
                    <li><a href="#"><span class="fa fa-brands fa-facebook-f"></span></a></li>
                    <li><a href="#"><span class="fa fa-brands fa-twitter"></span></a></li>
                    <li><a href="#"><span class="fa fa-brands fa-instagram"></span></a></li>
                    <li><a href="#"><span class="fa fa-brands fa-linkedin"></span></a></li>
                </ul>
            </div>

            <div class="col-lg-8">
                <div class="row links-wrap">
                    <div class="col-6 col-sm-6 col-md-3">
                        <ul class="list-unstyled">
                            <li><a href="#">About us</a></li>
                            <li><a href="#">Services</a></li>
                            <li><a href="#">Blog</a></li>
                            <li><a href="#">Contact us</a></li>
                        </ul>
                    </div>

                    <div class="col-6 col-sm-6 col-md-3">
                        <ul class="list-unstyled">
                            <li><a href="#">Support</a></li>
                            <li><a href="#">Knowledge base</a></li>
                            <li><a href="#">Live chat</a></li>
                        </ul>
                    </div>

                    <div class="col-6 col-sm-6 col-md-3">
                        <ul class="list-unstyled">
                            <li><a href="#">Jobs</a></li>
                            <li><a href="#">Our team</a></li>
                            <li><a href="#">Leadership</a></li>
                            <li><a href="#">Privacy Policy</a></li>
                        </ul>
                    </div>

                    <div class="col-6 col-sm-6 col-md-3">
                        <ul class="list-unstyled">
                            <li><a href="#">Nordic Chair</a></li>
                            <li><a href="#">Kruzo Aero</a></li>
                            <li><a href="#">Ergonomic Chair</a></li>
                        </ul>
                    </div>
                </div>
            </div>

        </div>

        <div class="border-top copyright">
            <div class="row pt-4">
                <div class="col-lg-6">
                    <p class="mb-2 text-center text-lg-start">Copyright &copy;<script>document.write(new Date().getFullYear());</script>
                        . All Rights Reserved. &mdash; Designed with love by <a href="https://untree.co">Untree.co</a>
                        <!-- License information: https://untree.co/license/ -->
                    </p>
                </div>

                <div class="col-lg-6 text-center text-lg-end">
                    <ul class="list-unstyled d-inline-flex ms-auto">
                        <li class="me-4"><a href="#">Terms &amp; Conditions</a></li>
                        <li><a href="#">Privacy Policy</a></li>
                    </ul>
                </div>

            </div>
        </div>

    </div>
</footer>
<!-- End Footer Section -->


<script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
<script src="{% static 'js/tiny-slider.js' %}"></script>
<script src="{% static 'js/custom.js' %}"></script>
</body>

</html>