web/apps/shop/urls.py
from django.urls import path
from .views import HomePageView, AboutPageView, ContactPageView, ShopPageView, ProductDetailPageView, \
    ProductCreatePageView, FilterProductsPageView, CategoryPageView, SearchView, FavouritesView, FavouritesAddView, \
    CardView, CardAddView, CardDeleteView, FavouriteDeleteView

app_name = 'shop'
urlpatterns = [
    path('', HomePageView.as_view(), name='home'),
    path('about-us/', AboutPageView.as_view(), name='about'),
    path('contact/', ContactPageView.as_view(), name='contact'),
    path('filter/', FilterProductsPageView.as_view(), name='filter'),
    path('shop/search/', SearchView.as_view(), name='search'),
    path('shop/category/<int:id>', CategoryPageView.as_view(), name='category'),
    path('shop/', ShopPageView.as_view(), name='shop'),
    path('products/<int:pk>', ProductDetailPageView.as_view(), name='product-detail'),
    path('product-create/', ProductCreatePageView.as_view(), name='product-create'),
    path('favourites/', FavouritesView.as_view(), name='favourite-list'),
    path('favourite-add/<int:product_id>/', FavouritesAddView.as_view(), name='favourite-add'),
    path('favourite-delete/<int:product_id>/', FavouriteDeleteView.as_view(), name='favourite-delete'),
    path('cards/', CardView.as_view(), name='card-list'),
    path('card-add/<int:product_id>/', CardAddView.as_view(), name='card-add'),
    path('card-delete/<int:product_id>/', CardDeleteView.as_view(), name='card-delete'),
]

web/apps/users/urls.py
from django.urls import path

from apps.users.views import UserLoginView, register_view, UserProfileView, logout_view, user_update_view, UserUpdateView

app_name = 'users'
urlpatterns = [
    path('login/', UserLoginView.as_view(), name="login"),
    # path('register/', UserRegisterView.as_view(), name="register"),
    path('register/', register_view, name="register"),
    path('user-profile/', UserProfileView.as_view(), name="user-profile"),
    path('user-update/', UserUpdateView.as_view(), name="user-update"),
    # path('user-update/', user_update_view, name="user-update"),
    # path('user-update/<int:id>', UserUpdateView.as_view(), name="user-update"),
    path('logout/', logout_view, name="logout"),
]

web/config/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from config import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('apps.store.urls')),
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

web/apps/users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models

from apps.shared.models import AbstractBaseModel


class User(AbstractUser, AbstractBaseModel):
    avatar = models.ImageField(upload_to="avatars/", blank=True)
    balance = models.DecimalField(max_digits=10, decimal_places=2, default=1000)
    birth_date = models.DateField(null=True, blank=True)
    slug = models.SlugField(unique=True)

web/apps/users/forms.py
from django.core.exceptions import ValidationError
from django.forms import ModelForm, IntegerField, Widget, Textarea, ImageField, CharField, PasswordInput, TextInput, \
    Form, FileInput, FileField

from apps.users.models import User


class UserLoginForm(Form):
    username = CharField(max_length=28, widget=TextInput(
        attrs={'class': 'form-control', 'placeholder': 'Username'}
    ))
    password = CharField(max_length=28, widget=PasswordInput(
        attrs={'class': 'form-control', 'placeholder': 'Password'}
    ))


class UserRegisterForm(ModelForm):
    password1 = CharField(max_length=28, widget=PasswordInput(
        attrs={'id': 'password', 'type': 'password'}))
    password2 = CharField(max_length=28, widget=PasswordInput(
        attrs={'id': 'password', 'type': 'password'}))
    avatar = FileField(widget=FileInput(attrs={'class': 'form-control'}))

    def save(self, commit=True):
        user = super().save(commit)
        password1 = self.cleaned_data.get("password1")
        password2 = self.cleaned_data.get("password2")
        if password1 == password2:
            user.set_password(password1)
            user.save()
        else:
            raise ValidationError("Passwords must be match")

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields:
            self.fields[field].widget.attrs.update({'class': "form-control"})

    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'email', 'username', 'password1', 'password2', 'avatar', 'birth_date', 'slug')


class UserUpdateForm(ModelForm):
    class Meta:
        password1 = CharField(max_length=28, widget=PasswordInput(
            attrs={'id': 'password', 'type': 'password'}))
        password2 = CharField(max_length=28, widget=PasswordInput(
            attrs={'id': 'password', 'type': 'password'}))
        avatar = FileField(widget=FileInput(attrs={'class': 'form-control'}))

        def save(self, commit=True):
            user = super().save(commit)
            password1 = self.cleaned_data.get("password1")
            password2 = self.cleaned_data.get("password2")
            if password1 == password2:
                user.set_password(password1)
                user.save()
            else:
                raise ValidationError("Passwords must be match")

        def __init__(self, *args, **kwargs):
            super().__init__(*args, **kwargs)
            for field in self.fields:
                self.fields[field].widget.attrs.update({'class': "form-control"})

        class Meta:
            model = User
            fields = ('first_name', 'last_name', 'email', 'username', 'password1', 'password2', 'avatar', 'birth_date', 'slug')

web/apps/users/views.py
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import AuthenticationForm
from django.contrib import messages
from django.shortcuts import render, redirect, get_object_or_404
from django.views import View

from apps.users.forms import UserRegisterForm, UserLoginForm, UserUpdateForm
from apps.shop.models import Product


def register_view(request):
    form = UserRegisterForm()
    if request.method == 'POST':
        form = UserRegisterForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            messages.success(request, 'User successfully registered')
            return redirect("users:login")
        else:
            return render(request, 'users/register.html', {'form': form})
    else:
        return render(request, 'users/register.html', {'form': form})


# class UserRegisterView(View):
#     def get(self, request):
#         form = UserRegisterForm()
#         return render(request, "users/register.html", context={"form": form})
#
#     def post(self, request):
#         create_form = UserRegisterForm(request.POST, request.FILES)
#         if create_form.is_valid():
#             create_form.save()
#             return redirect("users:login")
#         else:
#             context = {
#                 "form": create_form
#             }
#             return render(request, "users/register.html", context=context)


from apps.users.models import User


class UserLoginView(View):
    def get(self, request):
        form = UserLoginForm()
        context = {'form': form}
        return render(request, 'users/login.html', context)

    def post(self, request):
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            username = form.cleaned_data.get("username")
            password = form.cleaned_data.get("password")
            user = authenticate(username=username, password=password)
            if user is not None:
                login(request, user)
                messages.info(request, f"You have logged in as {username}")
                return redirect('shop:home')
            else:
                messages.error(request, "Invalid username or password")
        else:
            return render(request, "users/login.html", {"form": form})


def user_update_view(request, id):
    if request.method == 'POST':
        if request.user.is_authenticated:
            user = User.objects.get(id=request.user.id)
            form = UserUpdateForm(request.POST or None, request.FILES, instance=user)
            if form.is_valid():
                form.save()

                login(request, user)
                messages.success(request, 'User successfully updated')
                return redirect("users:user-profile")
            return render(request, 'users/user-update.html', {'form': form})
        else:
            messages.error(request, "You Must be Logged in To Access This Page!")
            return redirect("shop:home")
    else:
        form = UserUpdateForm()
        return render(request, 'users/user-update.html', {'form': form})


@login_required
def logout_view(request):
    messages.info(request, f"{request.user.username} user successfully loged out")
    logout(request)
    return redirect("shop:home")


class UserProfileView(View):
    def get(self, request):
        products = Product.objects.filter(seller__username=request.user.username)
        user = get_object_or_404(User, username=request.user.username)
        first_name = user.first_name
        last_name = user.last_name
        return render(request, 'users/user-profile.html', {"products": products,
                                                           'first_name': first_name,
                                                           'last_name': last_name,
                                                           'user': user})


class UserUpdateView(View):
    def get(self, request, id):
        user = User.objects.get(id=id)
        form = UserUpdateForm
        return render(request, 'users/user-update.html', {'form': form})

    def post(self, request):
        if request.user.is_authenticated:
            user = User.objects.get(id=request.user.id)
            form = UserUpdateForm(request.POST or None, request.FILES, instance=user)
            if form.is_valid():
                form.save()

                login(request, user)
                messages.success(request, 'User successfully updated')
                return redirect("users:user-profile")
            return render(request, 'users/user-update.html', {'form': form})
        else:
            messages.error(request, "You Must be Logged in To Access This Page!")
            return redirect("shop:home")

web/templates/users/login.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
    <div class="container my-5">
    <h3>Login Page</h3>
    <div class="col-4 mt-3">
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit" class="btn btn-success mt-2">Log in</button>
        </form>
    </div>
    </div>
{% endblock %}

web/templates/users/logout.html
{% extends "base.html" %}

{% load static %}

{% block body %}

    <form method="post">
        {% csrf_token %}
        Are you sure to Log Out
        <a>
            <button type="submit">Yes</button>
        </a>

    </form>
    <a href="{% url 'shop:home' %}">
        <button>No</button>
    </a>
{% endblock %}

web/templates/users/register.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
    <div class="container my-5">
    <h3 class="text-success">Register Page</h3>
    <div class="col-4 mt-3">
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit" class="btn btn-success mt-2">Sign up</button>
        </form>
    </div>
    </div>
{% endblock %}

web/templates/users/user-profile.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
    <div class="my-5 container">
        <div class="row mb-4">
            <div class="text-center">
                <img class="col-3 rounded-pill" src="{{ user.avatar.url }}" class="rounded" alt="...">
            </div>
        </div>
        <div class="text-center">
            <h1>{{ user.first_name }} {{ user.last_name }}</h1>
            <p class="text-secondary fs-4">{{ user.username }}</p>
        </div>
        <div class="row my-5">
            <span class="col-6 fs-2 text-start"><strong>Email:</strong></span><span
                class="col-6 fs-2 text-end">{{ user.email }}</span><br><br>
            <span class="col-6 fs-2 text-start"><strong>Born date:</strong></span><span
                class="col-6 fs-2 text-end">{{ user.born }}</span><br><br>
            <span class="text-end mt-5"><a href="{% url 'users:user-update'%}"><button
                    class="btn btn-outline-success px-4 py-2 fs-3">Update</button></a></span>
        </div>
        <div class="row">
            <h1 class="mt-5">My products:</h1>
            {% for product in products %}
            <div class="d-flex col-4 p-2 pb-3 mt-2">
                <div class="product-wap card rounded-0">
                    <div class="card rounded-0">
                        <img class="card-img rounded-0 img-fluid" src="{{ product.cover.url }}">
                        <div class="card-img-overlay rounded-0 product-overlay d-flex align-items-center justify-content-center">
                            <ul class="list-unstyled">
                                <li><a class="btn btn-success text-white" href="product-detail.html"><i
                                        class="far fa-heart"></i></a></li>
                                <li><a class="btn btn-success text-white mt-2" href="product-detail.html"><i
                                        class="far fa-eye"></i></a></li>
                                <li><a class="btn btn-success text-white mt-2" href="product-detail.html"><i
                                        class="fas fa-cart-plus"></i></a></li>
                            </ul>
                        </div>
                    </div>
                    <div class="card-body">
                        <a href="product-detail.html" class="h3 text-decoration-none">{{ product.name }}</a>
                        <ul class="w-100 list-unstyled d-flex justify-content-between mb-0">
                            <li><span class="text-secondary fs-6">{{ product.brand }}</span></li>
                            <li class="pt-2">
                                <span class="product-color-dot color-dot-red float-left rounded-circle ml-1"></span>
                                <span class="product-color-dot color-dot-blue float-left rounded-circle ml-1"></span>
                                <span class="product-color-dot color-dot-black float-left rounded-circle ml-1"></span>
                                <span class="product-color-dot color-dot-light float-left rounded-circle ml-1"></span>
                                <span class="product-color-dot color-dot-green float-left rounded-circle ml-1"></span>
                            </li>
                        </ul>
                        <ul class="list-unstyled d-flex justify-content-center mb-1">
                            <li>
                                <i class="text-warning fa fa-star"></i>
                                <i class="text-warning fa fa-star"></i>
                                <i class="text-warning fa fa-star"></i>
                                <i class="text-warning fa fa-star"></i>
                                <i class="text-muted fa fa-star"></i>
                            </li>
                        </ul>
                        <p class="text-center mb-0">${{ product.price }}</p>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
{% endblock %}

web/templates/users/user-update.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
    <div class="container my-5">
    <h3 class="text-success">User Update Page</h3>
    <div class="col-4 mt-3">
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit" class="btn btn-success mt-2">Save</button>
        </form>
    </div>
    </div>
{% endblock %}